"""initial schema

Revision ID: 5c3d752bd3a0
Revises: 
Create Date: 2026-09-09 17:00:27.244875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c3d752bd3a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('human_review_recommended', sa.Boolean(), nullable=True),
    sa.Column('rationale', sa.String(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.String(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=True),
    sa.Column('rule_based_tier', sa.String(), nullable=True),
    sa.Column('llm_tier', sa.String(), nullable=True),
    sa.Column('integrity_ok', sa.Boolean(), nullable=True),
    sa.Column('trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_runs_created_at'), 'investigation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_runs_ticker'), 'investigation_runs', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_tolerance', sa.String(), nullable=False),
    sa.Column('investment_horizon', sa.String(), nullable=False),
    sa.Column('position_size_pct', sa.Float(), nullable=False),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_investor_profiles_user_name')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.String(), nullable=False),
    sa.Column('reason_key', sa.String(), nullable=True),
    sa.Column('reason_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_ticker'), 'purchases', ['ticker'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('reasons',
    sa.Column('reason_key', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('comparison', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('denominator_metric', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('instant', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('reason_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasons')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_ticker'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('investor_profiles')
    op.drop_table('users')
    op.drop_index(op.f('ix_investigation_runs_ticker'), table_name='investigation_runs')
    op.drop_index(op.f('ix_investigation_runs_created_at'), table_name='investigation_runs')
    op.drop_table('investigation_runs')
    # ### end Alembic commands ###
