"""add notifications table and last_notified_status

Revision ID: d0a230e023fc
Revises: 5c3d752bd3a0
Create Date: 2026-09-14 17:44:45.033149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a230e023fc'
down_revision: Union[str, None] = '5c3d752bd3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('last_notified_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'last_notified_status')
    # ### end Alembic commands ###
